/*
 * generated by Xtext 2.17.0
 */
package de.th_koeln.nt.fowler.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class FowlerProposalProvider extends AbstractFowlerProposalProvider {
}
