/*
 * generated by Xtext 2.17.0
 */
package de.th_koeln.nt.fowler.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class FowlerUiModule extends AbstractFowlerUiModule {
}
