/*
 * generated by Xtext 2.17.0
 */
package de.th_koeln.nt.fowler


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FowlerStandaloneSetup extends FowlerStandaloneSetupGenerated {

	def static doSetup() {
		new FowlerStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
