/*
 * generated by Xtext 2.12.0
 */
package de.th_koeln.nt.fowler.tests

import com.google.inject.Inject
import de.th_koeln.nt.fowler.fowler.Statemachine
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(FowlerInjectorProvider)
class FowlerParsingTest {
	@Inject
	ParseHelper<Statemachine> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
