/*
 * generated by Xtext 2.17.0
 */
package de.th_koeln.nt.fowler.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class FowlerScopeProvider extends AbstractFowlerScopeProvider {

}
